name: Build

on:
    push:
        branches:
            - main
            - feature/*

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1

            - name: CI checks
              run: |
                  python -m pip install pipenv
                  make
