name: Release

on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1

            - name: Release
              run: |
                  python -m pip install pipenv
                  TWINE_USERNAME="${{ secrets.TWINE_USERNAME }}" \
                  TWINE_PASSWORD="${{ secrets.TWINE_PASSWORD }}" \
                  make publish
